# Change this variable to the RTL path of your own design
set RTL "${ROOT}/pulpino"
set search_path "${RTL}"

set FILESV "
${RTL}/ips/axi/axi_slice_dc/dc_full_detector.v
${RTL}/ips/axi/axi_slice_dc/dc_token_ring_fifo_dout.v
${RTL}/ips/axi/axi_slice_dc/dc_token_ring_fifo_din.v
${RTL}/ips/axi/axi_slice_dc/dc_synchronizer.v
${RTL}/ips/axi/axi_slice_dc/dc_token_ring.v
${RTL}/ips/axi/axi_slice_dc/dc_data_buffer.v
${RTL}/ips/axi/axi_node/defines.v
${RTL}/ips/adv_dbg_if/rtl/adbg_lint_defines.v
${RTL}/ips/adv_dbg_if/rtl/adbg_defines.v
${RTL}/ips/adv_dbg_if/rtl/syncflop.v
${RTL}/ips/adv_dbg_if/rtl/bytefifo.v
${RTL}/ips/adv_dbg_if/rtl/adbg_tap_defines.v
${RTL}/ips/adv_dbg_if/rtl/syncreg.v
${RTL}/ips/adv_dbg_if/rtl/adbg_or1k_defines.v
${RTL}/ips/adv_dbg_if/rtl/adbg_tap_top.v
${RTL}/ips/adv_dbg_if/rtl/adbg_axi_defines.v
${RTL}/ips/adv_dbg_if/rtl/adbg_crc32.v
"

set FILESSV "
${RTL}/rtl/includes/axi_bus.sv
${RTL}/rtl/includes/debug_bus.sv
${RTL}/rtl/includes/config.sv
${RTL}/rtl/includes/apb_bus.sv
${RTL}/rtl/includes/apu_defines.sv
${RTL}/ips/riscv/include/riscv_config.sv
${RTL}/ips/riscv/include/apu_core_package.sv
${RTL}/ips/riscv/include/apu_macros.sv
${RTL}/ips/riscv/include/riscv_defines.sv

${RTL}/rtl/components/dp_ram.sv
${RTL}/rtl/components/pulp_clock_inverter.sv
${RTL}/rtl/components/generic_fifo.sv
${RTL}/rtl/components/rstgen.sv
${RTL}/rtl/components/cluster_clock_mux2.sv
${RTL}/rtl/components/cluster_clock_gating.sv
${RTL}/rtl/components/cluster_clock_inverter.sv
${RTL}/rtl/components/pulp_clock_gating.sv
${RTL}/rtl/components/pulp_clock_mux2.sv
${RTL}/rtl/components/sp_ram_pulpino.sv




${RTL}/ips/riscv/riscv_hwloop_regs.sv
${RTL}/ips/riscv/riscv_hwloop_controller.sv
${RTL}/ips/riscv/riscv_fetch_fifo.sv
${RTL}/ips/riscv/riscv_register_file_latch.sv
${RTL}/ips/riscv/riscv_alu_div.sv

${RTL}/ips/riscv/riscv_register_file.sv
${RTL}/ips/riscv/riscv_id_stage.sv
${RTL}/ips/riscv/riscv_ex_stage.sv
${RTL}/ips/riscv/riscv_controller.sv


${RTL}/ips/riscv/riscv_mult.sv
${RTL}/ips/riscv/riscv_debug_unit.sv
${RTL}/ips/riscv/riscv_int_controller.sv
${RTL}/ips/riscv/riscv_prefetch_buffer.sv
${RTL}/ips/riscv/riscv_L0_buffer.sv
${RTL}/ips/riscv/riscv_alu_basic.sv
${RTL}/ips/riscv/riscv_if_stage.sv
${RTL}/ips/riscv/riscv_load_store_unit.sv
${RTL}/ips/riscv/riscv_compressed_decoder.sv
${RTL}/ips/riscv/riscv_prefetch_L0_buffer.sv
${RTL}/ips/riscv/riscv_cs_registers.sv
${RTL}/ips/riscv/verilator-model/dp_ram.sv
${RTL}/ips/riscv/verilator-model/top.sv
${RTL}/ips/riscv/verilator-model/ram.sv
${RTL}/ips/riscv/verilator-model/cluster_clock_gating.sv
${RTL}/ips/riscv/riscv_alu.sv
${RTL}/ips/riscv/riscv_core.sv
${RTL}/ips/riscv/riscv_apu_disp.sv
${RTL}/ips/axi/axi_slice_dc/axi_slice_dc_master.sv
${RTL}/ips/axi/axi_slice_dc/axi_slice_dc_slave.sv
${RTL}/ips/axi/axi2apb/AXI_2_APB_32.sv
${RTL}/ips/axi/axi2apb/axi2apb.sv
${RTL}/ips/axi/axi2apb/AXI_2_APB.sv
${RTL}/ips/axi/axi2apb/axi2apb32.sv
${RTL}/ips/axi/axi_node/axi_address_decoder_BR.sv
${RTL}/ips/axi/axi_node/axi_address_decoder_DW.sv
${RTL}/ips/axi/axi_node/axi_request_block.sv
${RTL}/ips/axi/axi_node/axi_regs_top.sv
${RTL}/ips/axi/axi_node/axi_RR_Flag_Req.sv
${RTL}/ips/axi/axi_node/axi_response_block.sv
${RTL}/ips/axi/axi_node/axi_FanInPrimitive_Req.sv
${RTL}/ips/axi/axi_node/axi_ArbitrationTree.sv
${RTL}/ips/axi/axi_node/axi_address_decoder_AR.sv
${RTL}/ips/axi/axi_node/axi_node_wrap_with_slices.sv
${RTL}/ips/axi/axi_node/axi_node_wrap.sv
${RTL}/ips/axi/axi_node/axi_DW_allocator.sv
${RTL}/ips/axi/axi_node/axi_BW_allocator.sv
${RTL}/ips/axi/axi_node/axi_BR_allocator.sv
${RTL}/ips/axi/axi_node/apb_regs_top.sv
${RTL}/ips/axi/axi_node/axi_AW_allocator.sv
${RTL}/ips/axi/axi_node/axi_multiplexer.sv
${RTL}/ips/axi/axi_node/axi_node.sv
${RTL}/ips/axi/axi_node/axi_address_decoder_AW.sv
${RTL}/ips/axi/axi_node/axi_AR_allocator.sv
${RTL}/ips/axi/axi_node/axi_address_decoder_BW.sv
${RTL}/ips/axi/axi_spi_master/spi_master_axi_if.sv
${RTL}/ips/axi/axi_spi_master/spi_master_fifo.sv
${RTL}/ips/axi/axi_spi_master/spi_master_rx.sv
${RTL}/ips/axi/axi_spi_master/axi_spi_master.sv
${RTL}/ips/axi/axi_spi_master/spi_master_tx.sv
${RTL}/ips/axi/axi_spi_master/spi_master_controller.sv
${RTL}/ips/axi/axi_spi_master/spi_master_clkgen.sv
${RTL}/ips/axi/axi_mem_if_DP/tb_axi_write_only.sv
${RTL}/ips/axi/axi_mem_if_DP/axi_mem_if_SP.sv
${RTL}/ips/axi/axi_mem_if_DP/axi_read_only_ctrl.sv
${RTL}/ips/axi/axi_mem_if_DP/axi_mem_if_DP_hybr.sv
${RTL}/ips/axi/axi_mem_if_DP/axi_mem_if_DP.sv
${RTL}/ips/axi/axi_mem_if_DP/axi_mem_if_MP_Hybrid_multi_bank.sv
${RTL}/ips/axi/axi_mem_if_DP/tb_axi_DP.sv
${RTL}/ips/axi/axi_mem_if_DP/axi_write_only_ctrl.sv
${RTL}/ips/axi/axi_mem_if_DP/tb_axi_read_only.sv
${RTL}/ips/axi/axi_mem_if_DP/axi_mem_if_multi_bank.sv
${RTL}/ips/axi/axi_spi_slave/spi_slave_dc_fifo.sv
${RTL}/ips/axi/axi_spi_slave/spi_slave_controller.sv
${RTL}/ips/axi/axi_spi_slave/axi_spi_slave.sv
${RTL}/ips/axi/axi_spi_slave/spi_slave_tx.sv
${RTL}/ips/axi/axi_spi_slave/spi_slave_rx.sv
${RTL}/ips/axi/axi_spi_slave/spi_slave_axi_plug.sv
${RTL}/ips/axi/axi_spi_slave/spi_slave_regs.sv
${RTL}/ips/axi/axi_spi_slave/spi_slave_cmd_parser.sv
${RTL}/ips/axi/axi_spi_slave/spi_slave_syncro.sv
${RTL}/ips/axi/axi_slice/axi_r_buffer.sv
${RTL}/ips/axi/axi_slice/axi_slice.sv
${RTL}/ips/axi/axi_slice/axi_aw_buffer.sv
${RTL}/ips/axi/axi_slice/axi_ar_buffer.sv
${RTL}/ips/axi/axi_slice/axi_buffer.sv
${RTL}/ips/axi/axi_slice/axi_b_buffer.sv
${RTL}/ips/axi/axi_slice/axi_w_buffer.sv
${RTL}/ips/axi/core2axi/core2axi.sv
${RTL}/ips/apb/apb_pulpino/apb_pulpino.sv
${RTL}/ips/apb/apb_gpio/apb_gpio.sv
${RTL}/ips/apb/apb_timer/timer.sv
${RTL}/ips/apb/apb_timer/apb_timer.sv
${RTL}/ips/apb/apb_uart_sv/uart_rx.sv
${RTL}/ips/apb/apb_uart_sv/io_generic_fifo.sv
${RTL}/ips/apb/apb_uart_sv/apb_uart.sv
${RTL}/ips/apb/apb_uart_sv/uart_interrupt.sv
${RTL}/ips/apb/apb_uart_sv/apb_uart_sv.sv
${RTL}/ips/apb/apb_uart_sv/uart_tx.sv
${RTL}/ips/apb/apb_spi_master/spi_master_apb_if.sv
${RTL}/ips/apb/apb_spi_master/spi_master_fifo.sv
${RTL}/ips/apb/apb_spi_master/spi_master_rx.sv
${RTL}/ips/apb/apb_spi_master/apb_spi_master.sv
${RTL}/ips/apb/apb_spi_master/spi_master_tx.sv
${RTL}/ips/apb/apb_spi_master/spi_master_controller.sv
${RTL}/ips/apb/apb_spi_master/spi_master_clkgen.sv
${RTL}/ips/apb/apb_event_unit/generic_service_unit.sv
${RTL}/ips/apb/apb_event_unit/sleep_unit.sv
${RTL}/ips/apb/apb_event_unit/include/defines_event_unit.sv
${RTL}/ips/apb/apb_event_unit/apb_event_unit.sv
${RTL}/ips/apb/apb_fll_if/apb_fll_if.sv
${RTL}/ips/apb/apb2per/apb2per.sv
${RTL}/ips/apb/apb_i2c/apb_i2c.sv
${RTL}/ips/apb/apb_i2c/i2c_master_defines.sv
${RTL}/ips/apb/apb_i2c/i2c_master_bit_ctrl.sv
${RTL}/ips/apb/apb_i2c/i2c_master_byte_ctrl.sv
${RTL}/ips/apb/apb_node/apb_node.sv
${RTL}/ips/apb/apb_node/apb_node_wrap.sv
${RTL}/ips/fpu/hdl/fpu_v0.1/fp_fma_wrapper.sv
${RTL}/ips/fpu/hdl/fpu_v0.1/fpu_core.sv
${RTL}/ips/fpu/hdl/fpu_v0.1/fpu.sv
${RTL}/ips/fpu/hdl/fpu_v0.1/fpu_shared.sv
${RTL}/ips/fpu/hdl/fpu_v0.1/fpu_mult.sv
${RTL}/ips/fpu/hdl/fpu_v0.1/fpexc.sv
${RTL}/ips/fpu/hdl/fpu_v0.1/riscv_fpu.sv
${RTL}/ips/fpu/hdl/fpu_v0.1/fpu_add.sv
${RTL}/ips/fpu/hdl/fpu_v0.1/fpu_itof.sv
${RTL}/ips/fpu/hdl/fpu_v0.1/fpu_ftoi.sv
${RTL}/ips/fpu/hdl/fpu_v0.1/fpu_defs.sv
${RTL}/ips/fpu/hdl/fpu_v0.1/fpu_norm.sv
${RTL}/ips/fpu/hdl/fpu_v0.1/fpu_private.sv
${RTL}/ips/fpu/hdl/fpu_v0.1/defines_fpu.sv
${RTL}/ips/fpu/hdl/fpu_fmac/wallace.sv
${RTL}/ips/fpu/hdl/fpu_fmac/pp_generation.sv
${RTL}/ips/fpu/hdl/fpu_fmac/fpu_defs_fmac.sv
${RTL}/ips/fpu/hdl/fpu_fmac/fmac.sv
${RTL}/ips/fpu/hdl/fpu_fmac/LZA.sv
${RTL}/ips/fpu/hdl/fpu_fmac/aligner.sv
${RTL}/ips/fpu/hdl/fpu_fmac/booth_encoder.sv
${RTL}/ips/fpu/hdl/fpu_fmac/fpu_norm_fmac.sv
${RTL}/ips/fpu/hdl/fpu_fmac/adders.sv
${RTL}/ips/fpu/hdl/fpu_fmac/preprocess_fmac.sv
${RTL}/ips/fpu/hdl/fpu_fmac/booth_selector.sv
${RTL}/ips/fpu/hdl/fpu_fmac/CSA.sv
${RTL}/ips/fpu/hdl/fpu_utils/fpu_ff.sv
${RTL}/ips/fpu/hdl/fpu_div_sqrt_tp_nlp/preprocess.sv
${RTL}/ips/fpu/hdl/fpu_div_sqrt_tp_nlp/nrbd_nrsc_tp.sv
${RTL}/ips/fpu/hdl/fpu_div_sqrt_tp_nlp/fpu_norm_div_sqrt.sv
${RTL}/ips/fpu/hdl/fpu_div_sqrt_tp_nlp/control_tp.sv
${RTL}/ips/fpu/hdl/fpu_div_sqrt_tp_nlp/fpu_defs_div_sqrt_tp.sv
${RTL}/ips/fpu/hdl/fpu_div_sqrt_tp_nlp/iteration_div_sqrt.sv
${RTL}/ips/fpu/hdl/fpu_div_sqrt_tp_nlp/iteration_div_sqrt_first.sv
${RTL}/ips/fpu/hdl/fpu_div_sqrt_tp_nlp/div_sqrt_top_tp.sv
${RTL}/ips/adv_dbg_if/rtl/adbg_or1k_biu.sv
${RTL}/ips/adv_dbg_if/rtl/adbg_lint_module.sv
${RTL}/ips/adv_dbg_if/rtl/adbg_axionly_top.sv
${RTL}/ips/adv_dbg_if/rtl/adbg_lintonly_top.sv
${RTL}/ips/adv_dbg_if/rtl/adbg_axi_biu.sv
${RTL}/ips/adv_dbg_if/rtl/adbg_or1k_status_reg.sv
${RTL}/ips/adv_dbg_if/rtl/adbg_axi_module.sv
${RTL}/ips/adv_dbg_if/rtl/adbg_top.sv
${RTL}/ips/adv_dbg_if/rtl/adbg_or1k_module.sv
${RTL}/ips/adv_dbg_if/rtl/adv_dbg_if.sv
${RTL}/ips/adv_dbg_if/rtl/adbg_lint_biu.sv
${RTL}/ips/zero-riscy/zeroriscy_multdiv_fast.sv
${RTL}/ips/zero-riscy/zeroriscy_ex_block.sv
${RTL}/ips/zero-riscy/zeroriscy_compressed_decoder.sv
${RTL}/ips/zero-riscy/zeroriscy_register_file_ff.sv
${RTL}/ips/zero-riscy/zeroriscy_id_stage.sv
${RTL}/ips/zero-riscy/zeroriscy_load_store_unit.sv
${RTL}/ips/zero-riscy/zeroriscy_cs_registers.sv
${RTL}/ips/zero-riscy/include/zeroriscy_tracer_defines.sv
${RTL}/ips/zero-riscy/include/zeroriscy_config.sv
${RTL}/ips/zero-riscy/include/zeroriscy_defines.sv
${RTL}/ips/zero-riscy/zeroriscy_tracer.sv
${RTL}/ips/zero-riscy/zeroriscy_register_file.sv
${RTL}/ips/zero-riscy/zeroriscy_if_stage.sv
${RTL}/ips/zero-riscy/zeroriscy_controller.sv
${RTL}/ips/zero-riscy/zeroriscy_prefetch_buffer.sv
${RTL}/ips/zero-riscy/zeroriscy_int_controller.sv
${RTL}/ips/zero-riscy/zeroriscy_alu.sv
${RTL}/ips/zero-riscy/zeroriscy_fetch_fifo.sv
${RTL}/ips/zero-riscy/zeroriscy_multdiv_slow.sv
${RTL}/ips/zero-riscy/zeroriscy_decoder.sv
${RTL}/ips/zero-riscy/zeroriscy_core.sv
${RTL}/ips/zero-riscy/zeroriscy_debug_unit.sv

${RTL}/rtl/core2axi_wrap.sv
${RTL}/rtl/ram_mux.sv
${RTL}/rtl/dp_ram_wrap.sv
${RTL}/rtl/apb_mock_uart.sv
${RTL}/rtl/clk_rst_gen.sv
${RTL}/rtl/boot_code.sv
${RTL}/rtl/axi_node_intf_wrap.sv
${RTL}/rtl/axi_spi_slave_wrap.sv
${RTL}/rtl/periph_bus_wrap.sv
${RTL}/rtl/core_region.sv
${RTL}/rtl/axi2apb_wrap.sv
${RTL}/rtl/boot_rom_wrap.sv
${RTL}/rtl/axi_mem_if_SP_wrap.sv
${RTL}/rtl/instr_ram_wrap.sv
${RTL}/rtl/axi_slice_wrap.sv
${RTL}/rtl/random_stalls.sv
${RTL}/rtl/peripherals.sv
${RTL}/rtl/sp_ram_wrap.sv
${RTL}/rtl/pulpino_top.sv
"


